export const marketingNavItems = [
  { href: "/admin/marketing", label: "Dashboard", exact: true },
  { href: "/admin/marketing/brand-standards", label: "Brand standards" },
  { href: "/admin/marketing/promotions", label: "Promotion engine" },
  { href: "/admin/marketing/coupons", label: "Coupons" },
  { href: "/admin/marketing/flash-sales", label: "Flash sales" },
  { href: "/admin/marketing/wallet", label: "Wallet" },
  { href: "/admin/marketing/rewards", label: "Reward points" },
  { href: "/admin/marketing/referral", label: "Referral" },
  { href: "/admin/marketing/affiliate", label: "Affiliate" },
  { href: "/admin/marketing/push", label: "Push notifications" },
  { href: "/admin/marketing/email-campaigns", label: "Email campaigns" },
  { href: "/admin/marketing/abandoned-cart", label: "Abandoned cart" },
  { href: "/admin/marketing/recommendations", label: "Recommendations" },
  { href: "/admin/marketing/recently-viewed", label: "Recently viewed" },
  { href: "/admin/marketing/reviews", label: "Review system" },
  { href: "/admin/marketing/comparison", label: "Product comparison" },
  { href: "/admin/marketing/analytics", label: "Analytics" },
  { href: "/admin/marketing/automation", label: "Automation" },
  { href: "/admin/marketing/scheduling", label: "Campaign scheduling" },
] as const;
