/**
 * Sample variables for admin previews and local smoke checks.
 * Not used in production sends — callers supply live data.
 */
import type { EmailTemplateKey, EmailVarsMap } from "@/emails/types";

const appUrl = "https://www.veronicamark.com";

export const emailPreviewSamples: { [K in EmailTemplateKey]: EmailVarsMap[K] } = {
  "auth.email_verification": {
    recipientName: "Camille",
    ctaUrl: `${appUrl}/auth/verify-email?token=preview`,
    expiresIn: "one hour",
  },
  "auth.password_reset": {
    recipientName: "Camille",
    ctaUrl: `${appUrl}/auth/reset-password?token=preview`,
    expiresIn: "one hour",
  },
  "auth.welcome": { recipientName: "Camille", appUrl },
  "auth.password_changed": { recipientName: "Camille", appUrl },
  "auth.account_disabled": {
    recipientName: "Camille",
    reason: "Unusual activity review",
    appUrl,
  },
  "staff.admin_invite": {
    recipientName: "Amaka",
    roleLabel: "Super Admin",
    inviterName: "Platform Ops",
    ctaUrl: `${appUrl}/auth/accept-invite?token=preview`,
  },
  "staff.brand_manager_invite": {
    recipientName: "Ifeoma",
    roleLabel: "Brand Manager",
    brandName: "VMA SCENTS",
    inviterName: "Platform Ops",
    ctaUrl: `${appUrl}/auth/accept-invite?token=preview`,
  },
  "order.confirmation": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0001",
    orderTotalLabel: "₦93,500",
    shippingMethod: "Intra-city drop · Rivers",
    shippingAddress: "Port Harcourt, Rivers State",
    items: [{ name: "Noir Éclat Eau de Parfum · 100 ml", quantity: 1, priceLabel: "₦85,000" }],
    currencyNote: "All product prices include tax.",
    invoiceUrl: `${appUrl}/invoices/VM-2026-0001`,
    appUrl,
  },
  "order.payment_failed": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0009",
    orderTotalLabel: "₦45,000",
    appUrl,
  },
  "order.processing": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0001",
    appUrl,
  },
  "order.packed": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0001",
    appUrl,
  },
  "order.shipped": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0001",
    trackingNumber: "NG-VM-88421",
    estimatedDelivery: "2–4 business days",
    trackingUrl: `${appUrl}/track-order`,
    appUrl,
  },
  "order.out_for_delivery": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0001",
    trackingUrl: `${appUrl}/track-order`,
    appUrl,
  },
  "order.delivered": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0001",
    appUrl,
  },
  "order.cancelled": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0008",
    cancelReason: "Requested before dispatch",
    appUrl,
  },
  "order.completed": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0001",
    appUrl,
  },
  "return.requested": {
    recipientName: "Camille",
    returnNumber: "RT-2026-0012",
    orderNumber: "VM-2026-0002",
    reason: "Changed mind",
    appUrl,
  },
  "return.approved": {
    recipientName: "Camille",
    returnNumber: "RT-2026-0012",
    orderNumber: "VM-2026-0002",
    appUrl,
  },
  "return.rejected": {
    recipientName: "Camille",
    returnNumber: "RT-2026-0013",
    orderNumber: "VM-2026-0003",
    reason: "Outside return window",
    appUrl,
  },
  "refund.processed": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0002",
    refundAmountLabel: "₦30,000",
    refundMethod: "Original payment method",
    appUrl,
  },
  "rewards.points_earned": {
    recipientName: "Camille",
    points: 210,
    pointsBalance: 1840,
    orderNumber: "VM-2026-0004",
    appUrl,
  },
  "rewards.tier_upgraded": {
    recipientName: "Camille",
    tierName: "Platinum",
    previousTier: "Gold",
    pointsBalance: 2200,
    appUrl,
  },
  "wallet.credit_received": {
    recipientName: "Camille",
    creditAmountLabel: "₦25,000",
    balanceLabel: "₦42,500",
    reason: "Referral reward",
    appUrl,
  },
  "referral.invite": {
    inviterName: "Camille",
    referralCode: "CAMILLE-VM",
    rewardLabel: "you both receive wallet credit after the first eligible order",
    ctaUrl: `${appUrl}/r/CAMILLE-VM`,
  },
  "referral.reward": {
    recipientName: "Camille",
    rewardLabel: "₦25,000 wallet credit",
    appUrl,
  },
  "wishlist.back_in_stock": {
    recipientName: "Camille",
    productName: "Velvet Iris Eau de Parfum",
    brandName: "VMA SCENTS",
    priceLabel: "₦72,000",
    ctaUrl: `${appUrl}/products/velvet-iris`,
  },
  "wishlist.price_drop": {
    recipientName: "Camille",
    productName: "Soleil Néroli",
    previousPriceLabel: "₦68,000",
    priceLabel: "₦59,500",
    ctaUrl: `${appUrl}/products/soleil-neroli`,
  },
  "cart.abandoned_1": {
    recipientName: "Camille",
    cartTotalLabel: "₦85,000",
    items: [{ name: "Noir Éclat Eau de Parfum", quantity: 1, priceLabel: "₦85,000" }],
    ctaUrl: `${appUrl}/bag`,
  },
  "cart.abandoned_2": {
    recipientName: "Camille",
    cartTotalLabel: "₦85,000",
    couponCode: "WELCOME15",
    items: [{ name: "Noir Éclat Eau de Parfum", quantity: 1, priceLabel: "₦85,000" }],
    ctaUrl: `${appUrl}/checkout`,
  },
  "review.request": {
    recipientName: "Camille",
    orderNumber: "VM-2026-0001",
    productName: "Noir Éclat Eau de Parfum",
    ctaUrl: `${appUrl}/account/orders/VM-2026-0001`,
  },
  "lifecycle.winback": {
    recipientName: "Camille",
    headline: "The edit continues without you",
    offerLabel: "WELCOME15 on your next eligible order",
    ctaUrl: appUrl,
  },
  "newsletter.welcome": { recipientName: "Camille", ctaUrl: appUrl },
  "marketing.flash_sale": {
    recipientName: "Camille",
    campaignName: "August Grand Opening",
    headline: "August Grand Opening",
    offerLabel: "A limited curated selection",
    endsAtLabel: "7 Aug 2026",
    ctaUrl: `${appUrl}/flash-sale`,
  },
  "marketing.promotion": {
    recipientName: "Camille",
    headline: "New signatures in the edit",
    body: "Discover newly curated arrivals from trusted houses.",
    ctaUrl: appUrl,
  },
  "marketing.newsletter": {
    recipientName: "Camille",
    headline: "Notes from the house",
    body: "This month: warm woods, citrus openers, and enduring client favourites.",
    ctaUrl: appUrl,
  },
  "brand.low_stock": {
    recipientName: "Ifeoma",
    brandName: "VMA SCENTS",
    productName: "Noir Éclat · 100 ml",
    sku: "VM-NE-100",
    stockLevel: 3,
    threshold: 5,
    appUrl,
  },
  "brand.new_order": {
    recipientName: "Ifeoma",
    brandName: "VMA SCENTS",
    orderNumber: "VM-2026-0001",
    orderTotalLabel: "₦85,000",
    appUrl,
  },
  "brand.flash_sale_alert": {
    recipientName: "Ifeoma",
    brandName: "VMA SCENTS",
    flashSaleName: "August Grand Opening",
    metricLabel: "Units sold",
    metricValue: "48 in 2 hours",
    appUrl,
  },
  "contact.auto_reply": {
    senderName: "Camille Dubois",
    senderEmail: "camille@example.com",
    subject: "Fragrance recommendation",
    message: "Looking for a warm evening scent.",
    topic: "Advice",
    appUrl,
  },
  "contact.internal_notify": {
    senderName: "Camille Dubois",
    senderEmail: "camille@example.com",
    subject: "Fragrance recommendation",
    message: "Looking for a warm evening scent for an anniversary dinner.",
    topic: "Advice",
  },
  "admin.event": {
    recipientName: "Client services",
    eventTitle: "Order Paid · order confirmation · VM-2026-0001",
    summary: "Camille · customer@example.com · ₦93,500",
    details: [
      { label: "Order", value: "VM-2026-0001" },
      { label: "Customer email", value: "customer@example.com" },
      { label: "Total", value: "₦93,500" },
      { label: "Address line 1", value: "12 Ada George Rd" },
      { label: "City", value: "Port Harcourt" },
      { label: "State", value: "Rivers" },
      { label: "Country", value: "NG" },
    ],
    items: [{ name: "Noir Éclat Eau de Parfum · 100 ml", quantity: 1, priceLabel: "₦85,000" }],
    ctaUrl: `${appUrl}/admin/orders/VM-2026-0001`,
  },
};
