import {
  buildAuthAccountDisabled,
  buildAuthEmailVerification,
  buildAuthPasswordChanged,
  buildAuthPasswordReset,
  buildAuthWelcome,
  buildStaffAdminInvite,
  buildStaffBrandManagerInvite,
} from "@/emails/definitions/auth-staff";
import {
  buildCartAbandoned1,
  buildCartAbandoned2,
  buildLifecycleWinback,
  buildReferralInvite,
  buildReferralReward,
  buildReviewRequest,
  buildRewardsPointsEarned,
  buildRewardsTierUpgraded,
  buildWalletCreditReceived,
  buildWishlistBackInStock,
  buildWishlistPriceDrop,
} from "@/emails/definitions/loyalty-lifecycle";
import {
  buildBrandFlashSaleAlert,
  buildBrandLowStock,
  buildBrandNewOrder,
  buildContactAutoReply,
  buildContactInternalNotify,
  buildAdminEvent,
  buildMarketingFlashSale,
  buildMarketingNewsletter,
  buildMarketingPromotion,
  buildNewsletterWelcome,
} from "@/emails/definitions/marketing-brand-contact";
import {
  buildOrderCancelled,
  buildOrderCompleted,
  buildOrderConfirmation,
  buildOrderDelivered,
  buildOrderOutForDelivery,
  buildOrderPacked,
  buildOrderPaymentFailed,
  buildOrderProcessing,
  buildOrderShipped,
  buildRefundProcessed,
  buildReturnApproved,
  buildReturnRejected,
  buildReturnRequested,
} from "@/emails/definitions/orders-returns";
import { renderEmailShell, renderPlainText } from "@/emails/layout";
import type {
  EmailContent,
  EmailMeta,
  EmailTemplateKey,
  EmailVarsMap,
  RenderedEmail,
} from "@/emails/types";
import { EMAIL_TEMPLATE_KEYS } from "@/emails/types";

type BuilderMap = {
  [K in EmailTemplateKey]: (vars: EmailVarsMap[K]) => EmailContent;
};

const builders: BuilderMap = {
  "auth.email_verification": buildAuthEmailVerification,
  "auth.password_reset": buildAuthPasswordReset,
  "auth.welcome": buildAuthWelcome,
  "auth.password_changed": buildAuthPasswordChanged,
  "auth.account_disabled": buildAuthAccountDisabled,
  "staff.admin_invite": buildStaffAdminInvite,
  "staff.brand_manager_invite": buildStaffBrandManagerInvite,
  "order.confirmation": buildOrderConfirmation,
  "order.payment_failed": buildOrderPaymentFailed,
  "order.processing": buildOrderProcessing,
  "order.packed": buildOrderPacked,
  "order.shipped": buildOrderShipped,
  "order.out_for_delivery": buildOrderOutForDelivery,
  "order.delivered": buildOrderDelivered,
  "order.cancelled": buildOrderCancelled,
  "order.completed": buildOrderCompleted,
  "return.requested": buildReturnRequested,
  "return.approved": buildReturnApproved,
  "return.rejected": buildReturnRejected,
  "refund.processed": buildRefundProcessed,
  "rewards.points_earned": buildRewardsPointsEarned,
  "rewards.tier_upgraded": buildRewardsTierUpgraded,
  "wallet.credit_received": buildWalletCreditReceived,
  "referral.invite": buildReferralInvite,
  "referral.reward": buildReferralReward,
  "wishlist.back_in_stock": buildWishlistBackInStock,
  "wishlist.price_drop": buildWishlistPriceDrop,
  "cart.abandoned_1": buildCartAbandoned1,
  "cart.abandoned_2": buildCartAbandoned2,
  "review.request": buildReviewRequest,
  "lifecycle.winback": buildLifecycleWinback,
  "newsletter.welcome": buildNewsletterWelcome,
  "marketing.flash_sale": buildMarketingFlashSale,
  "marketing.promotion": buildMarketingPromotion,
  "marketing.newsletter": buildMarketingNewsletter,
  "brand.low_stock": buildBrandLowStock,
  "brand.new_order": buildBrandNewOrder,
  "brand.flash_sale_alert": buildBrandFlashSaleAlert,
  "contact.auto_reply": buildContactAutoReply,
  "contact.internal_notify": buildContactInternalNotify,
  "admin.event": buildAdminEvent,
};

export const emailTemplateMeta: Record<EmailTemplateKey, EmailMeta> = {
  "auth.email_verification": {
    key: "auth.email_verification",
    name: "Email verification",
    description: "Confirm email after signup or resend.",
    channel: "transactional",
    audience: "customer",
  },
  "auth.password_reset": {
    key: "auth.password_reset",
    name: "Password reset",
    description: "Secure password reset link.",
    channel: "transactional",
    audience: "customer",
  },
  "auth.welcome": {
    key: "auth.welcome",
    name: "Welcome",
    description: "Welcome after successful signup or verification.",
    channel: "transactional",
    audience: "customer",
  },
  "auth.password_changed": {
    key: "auth.password_changed",
    name: "Password changed",
    description: "Security notice when password changes.",
    channel: "transactional",
    audience: "customer",
  },
  "auth.account_disabled": {
    key: "auth.account_disabled",
    name: "Account disabled",
    description: "Notice when account access is restricted.",
    channel: "transactional",
    audience: "customer",
  },
  "staff.admin_invite": {
    key: "staff.admin_invite",
    name: "Admin invite",
    description: "Super Admin workspace invitation.",
    channel: "transactional",
    audience: "staff",
  },
  "staff.brand_manager_invite": {
    key: "staff.brand_manager_invite",
    name: "Brand Manager invite",
    description: "Brand Manager workspace invitation.",
    channel: "transactional",
    audience: "brand",
  },
  "order.confirmation": {
    key: "order.confirmation",
    name: "Order confirmation",
    description: "Order placed with reference and invoice link.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "order.payment_failed": {
    key: "order.payment_failed",
    name: "Payment failed",
    description: "Payment unsuccessful with retry guidance.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "order.processing": {
    key: "order.processing",
    name: "Order processing",
    description: "Order is being prepared.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "order.packed": {
    key: "order.packed",
    name: "Order packed",
    description: "Order packed and ready for dispatch.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "order.shipped": {
    key: "order.shipped",
    name: "Order shipped",
    description: "Dispatch confirmation with tracking.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "order.out_for_delivery": {
    key: "order.out_for_delivery",
    name: "Out for delivery",
    description: "Parcel is out for delivery.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "order.delivered": {
    key: "order.delivered",
    name: "Order delivered",
    description: "Delivery confirmation.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "order.cancelled": {
    key: "order.cancelled",
    name: "Order cancelled",
    description: "Order cancellation notice.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "order.completed": {
    key: "order.completed",
    name: "Order completed",
    description: "Order complete thank-you.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "return.requested": {
    key: "return.requested",
    name: "Return requested",
    description: "Return request acknowledgement.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "return.approved": {
    key: "return.approved",
    name: "Return approved",
    description: "Return approved with packing guidance.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "return.rejected": {
    key: "return.rejected",
    name: "Return rejected",
    description: "Return request declined.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "refund.processed": {
    key: "refund.processed",
    name: "Refund processed",
    description: "Refund issued confirmation.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "orders",
  },
  "rewards.points_earned": {
    key: "rewards.points_earned",
    name: "Points earned",
    description: "Loyalty points earned notice.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "loyalty",
  },
  "rewards.tier_upgraded": {
    key: "rewards.tier_upgraded",
    name: "Tier upgraded",
    description: "Loyalty tier upgrade congratulations.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "loyalty",
  },
  "wallet.credit_received": {
    key: "wallet.credit_received",
    name: "Wallet credit",
    description: "Wallet credit received.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "loyalty",
  },
  "referral.invite": {
    key: "referral.invite",
    name: "Referral invite",
    description: "Friend invitation from referral form.",
    channel: "marketing",
    audience: "customer",
  },
  "referral.reward": {
    key: "referral.reward",
    name: "Referral reward",
    description: "Referrer reward when invite converts.",
    channel: "transactional",
    audience: "customer",
    preferenceCategory: "loyalty",
  },
  "wishlist.back_in_stock": {
    key: "wishlist.back_in_stock",
    name: "Back in stock",
    description: "Wishlist item available again.",
    channel: "transactional",
    audience: "customer",
  },
  "wishlist.price_drop": {
    key: "wishlist.price_drop",
    name: "Price drop",
    description: "Wishlist item price update.",
    channel: "transactional",
    audience: "customer",
  },
  "cart.abandoned_1": {
    key: "cart.abandoned_1",
    name: "Abandoned cart · reminder 1",
    description: "First abandoned cart recovery email.",
    channel: "marketing",
    audience: "customer",
    preferenceCategory: "promotions",
  },
  "cart.abandoned_2": {
    key: "cart.abandoned_2",
    name: "Abandoned cart · reminder 2",
    description: "Second abandoned cart recovery email.",
    channel: "marketing",
    audience: "customer",
    preferenceCategory: "promotions",
  },
  "review.request": {
    key: "review.request",
    name: "Review request",
    description: "Post-delivery review invitation.",
    channel: "transactional",
    audience: "customer",
  },
  "lifecycle.winback": {
    key: "lifecycle.winback",
    name: "Win-back",
    description: "Lapsed buyer win-back with optional offer.",
    channel: "marketing",
    audience: "customer",
    preferenceCategory: "promotions",
  },
  "newsletter.welcome": {
    key: "newsletter.welcome",
    name: "Newsletter welcome",
    description: "Private list signup confirmation.",
    channel: "marketing",
    audience: "customer",
    preferenceCategory: "newsletter",
  },
  "marketing.flash_sale": {
    key: "marketing.flash_sale",
    name: "Flash sale announcement",
    description: "Timed opening edit / flash sale campaign.",
    channel: "marketing",
    audience: "customer",
    preferenceCategory: "promotions",
  },
  "marketing.promotion": {
    key: "marketing.promotion",
    name: "Promotion",
    description: "Generic promotional / brand launch email.",
    channel: "marketing",
    audience: "customer",
    preferenceCategory: "promotions",
  },
  "marketing.newsletter": {
    key: "marketing.newsletter",
    name: "Newsletter",
    description: "Recurring journal / newsletter edition.",
    channel: "marketing",
    audience: "customer",
    preferenceCategory: "newsletter",
  },
  "brand.low_stock": {
    key: "brand.low_stock",
    name: "Brand low stock",
    description: "Operational low-stock alert for Brand Managers.",
    channel: "operational",
    audience: "brand",
  },
  "brand.new_order": {
    key: "brand.new_order",
    name: "Brand new order",
    description: "New order alert for Brand Managers.",
    channel: "operational",
    audience: "brand",
  },
  "brand.flash_sale_alert": {
    key: "brand.flash_sale_alert",
    name: "Brand flash sale alert",
    description: "Live flash-sale performance alert.",
    channel: "operational",
    audience: "brand",
  },
  "contact.auto_reply": {
    key: "contact.auto_reply",
    name: "Contact auto-reply",
    description: "Auto-reply after Contact form submission.",
    channel: "transactional",
    audience: "customer",
  },
  "contact.internal_notify": {
    key: "contact.internal_notify",
    name: "Contact internal notify",
    description: "Internal notify to client services.",
    channel: "operational",
    audience: "internal",
  },
  "admin.event": {
    key: "admin.event",
    name: "Admin event copy",
    description: "Individually addressed admin copy of platform events with full submitted details.",
    channel: "operational",
    audience: "internal",
  },
};

export function listEmailTemplates(): EmailMeta[] {
  return EMAIL_TEMPLATE_KEYS.map((key) => emailTemplateMeta[key]);
}

export function renderEmail<K extends EmailTemplateKey>(
  key: K,
  vars: EmailVarsMap[K],
): RenderedEmail {
  const content = builders[key](vars);
  if (vars.previewText) {
    content.previewText = vars.previewText;
  }
  return {
    key,
    subject: content.subject,
    previewText: content.previewText,
    html: renderEmailShell(content),
    text: renderPlainText(content),
  };
}

export function isEmailTemplateKey(value: string): value is EmailTemplateKey {
  return (EMAIL_TEMPLATE_KEYS as readonly string[]).includes(value);
}
