/**
 * Perfume Invoice (C-GLOBAL / PEE VEE S.O. 846) — purchase catalog.
 * costPrice = invoice Rate (NGN). sellPrice = costPrice * 1.5. stock = Qty.
 */
export type InvoiceProduct = {
  name: string;
  qty: number;
  costPrice: number;
  category: "perfume" | "body";
};

export const INVOICE_PRODUCTS: InvoiceProduct[] = [
  { name: "Maahir Perfume", qty: 2, costPrice: 27000, category: "perfume" },
  { name: "Brulee Perfume", qty: 1, costPrice: 50500, category: "perfume" },
  { name: "Spectre Perfume Mix (French Avenue) 80ml", qty: 2, costPrice: 50000, category: "perfume" },
  { name: "Club De Nuit Limited Edition", qty: 2, costPrice: 103000, category: "perfume" },
  { name: "Oud For Glory 100ml Mix", qty: 4, costPrice: 27800, category: "perfume" },
  { name: "Ishq Al Shuyukh Gold Perfume 100ml", qty: 2, costPrice: 37500, category: "perfume" },
  { name: "Golden Bullet Top Gun Perfume 100ml", qty: 2, costPrice: 24000, category: "perfume" },
  { name: "Now Rave Perfume Mix 100ml", qty: 4, costPrice: 20400, category: "perfume" },
  { name: "Supremacy Collectors Edition 100ml", qty: 2, costPrice: 79000, category: "perfume" },
  { name: "Supremacy Perfume Not Only Intense 100ml", qty: 1, costPrice: 60000, category: "perfume" },
  { name: "Supremacy In Oud Perfume 100ml", qty: 1, costPrice: 62000, category: "perfume" },
  { name: "Club De Nuit Intense Man 105ml", qty: 2, costPrice: 44000, category: "perfume" },
  { name: "Club De Nuit Iconic 105ml", qty: 2, costPrice: 50000, category: "perfume" },
  { name: "Club De Nuit Sillage / Untold Mix", qty: 2, costPrice: 52000, category: "perfume" },
  { name: "Asad Bourbon Perfume 100ml", qty: 1, costPrice: 29000, category: "perfume" },
  { name: "Asad Black Lattafa 100ml", qty: 2, costPrice: 24500, category: "perfume" },
  { name: "Asad Elixir Perfume 100ml", qty: 2, costPrice: 24500, category: "perfume" },
  { name: "Breed Lovely Girl Perfume 100ml", qty: 1, costPrice: 25700, category: "perfume" },
  { name: "Breed My Man Perfume 100ml", qty: 1, costPrice: 33000, category: "perfume" },
  { name: "Breed Lovely Story Perfume 100ml", qty: 1, costPrice: 25700, category: "perfume" },
  { name: "Breed The Boss 100ml", qty: 1, costPrice: 29500, category: "perfume" },
  { name: "Vanilla Voyage Perfume", qty: 2, costPrice: 38000, category: "perfume" },
  { name: "Riggs Perfume 100ml", qty: 3, costPrice: 10300, category: "perfume" },
  { name: "Montwood Paris Perfume Mix 100ml", qty: 3, costPrice: 20200, category: "perfume" },
  { name: "Ajwad Lattafa Perfume 100ml", qty: 2, costPrice: 23000, category: "perfume" },
  { name: "Qaed Al Fursan Perfume 90ml White", qty: 1, costPrice: 14500, category: "perfume" },
  { name: "Qaed Al Fursan Perfume Black 90ml", qty: 1, costPrice: 20500, category: "perfume" },
  { name: "Addicted Silver Perfume 120ml", qty: 2, costPrice: 50000, category: "perfume" },
  { name: "Royal Taboo Perfume 100ml", qty: 2, costPrice: 62000, category: "perfume" },
  { name: "9PM Rebel Perfume 100ml", qty: 1, costPrice: 50000, category: "perfume" },
  { name: "9AM Pink 100ml", qty: 1, costPrice: 39000, category: "perfume" },
  { name: "9PM Elixir Perfume 100ml", qty: 1, costPrice: 50500, category: "perfume" },
  { name: "Giorgio Perfume Mix", qty: 2, costPrice: 14500, category: "perfume" },
  { name: "Liquid Burn Perfume 100ml", qty: 2, costPrice: 45600, category: "perfume" },
  { name: "Oud Touch Perfume Mix 100ml", qty: 2, costPrice: 30000, category: "perfume" },
  { name: "Musaman Black 100ml", qty: 2, costPrice: 39000, category: "perfume" },
  { name: "Eclaire Perfume 100ml Mix", qty: 2, costPrice: 28660, category: "perfume" },
  { name: "Dynasty Perfume 100ml", qty: 2, costPrice: 23500, category: "perfume" },
  { name: "Nebras Lattafa 100ml", qty: 2, costPrice: 38000, category: "perfume" },
  { name: "Pinnace Perfume 100ml", qty: 2, costPrice: 45750, category: "perfume" },
  { name: "Avanti 100ml Perfume", qty: 2, costPrice: 11800, category: "perfume" },
  { name: "Oud Noir Perfume 100ml", qty: 2, costPrice: 20600, category: "perfume" },
  { name: "Khamrah (Dukhan) 100ml", qty: 2, costPrice: 32000, category: "perfume" },
  { name: "Abraaj Valour Perfume 100ml", qty: 2, costPrice: 20300, category: "perfume" },
  { name: "Mocha Wood Perfume 100ml", qty: 2, costPrice: 28500, category: "perfume" },
  { name: "Oud Al Layl 100ml", qty: 2, costPrice: 11000, category: "perfume" },
  { name: "Al Faris Perfume 100ml", qty: 2, costPrice: 10800, category: "perfume" },
  { name: "Berries Weekend Perfume 100ml", qty: 2, costPrice: 14300, category: "perfume" },
  { name: "Opulent Perfume Dubai 100ml Mix", qty: 2, costPrice: 14800, category: "perfume" },
  { name: "Suave Perfume", qty: 2, costPrice: 14200, category: "perfume" },
  { name: "Floriana Rayhaan 100ml", qty: 1, costPrice: 25300, category: "perfume" },
  { name: "Rayhaan Obsidian Perfume", qty: 1, costPrice: 33000, category: "perfume" },
  { name: "Rayhaan Nocturno Perfume 100ml", qty: 1, costPrice: 23300, category: "perfume" },
  { name: "Rayhaan Corium 100ml", qty: 1, costPrice: 28500, category: "perfume" },
  { name: "Qissa Perfume Mix 100ml", qty: 2, costPrice: 17600, category: "perfume" },
  { name: "Salt Perfume 100ml", qty: 2, costPrice: 30000, category: "perfume" },
  { name: "Ameer Al Oud (Intense Oud) 100ml", qty: 2, costPrice: 22000, category: "perfume" },
  { name: "Saheb 70ml", qty: 2, costPrice: 21000, category: "perfume" },
  { name: "My Her Perfume 100ml", qty: 2, costPrice: 14000, category: "perfume" },
  { name: "Aventos Blue For Him Perfume", qty: 2, costPrice: 14000, category: "perfume" },
  { name: "Arabiyat Prestige Nyla Perfume 100ml", qty: 2, costPrice: 24000, category: "perfume" },
  { name: "Monsieur Intense Vanille 100ml", qty: 2, costPrice: 15500, category: "perfume" },
  { name: "Lamsat Harir 100ml Perfume", qty: 2, costPrice: 11000, category: "perfume" },
  { name: "Victoria Flower Orchid Perfume 100ml", qty: 2, costPrice: 16900, category: "perfume" },
  { name: "Oud Satin Perfume Mix 100ml", qty: 2, costPrice: 23250, category: "perfume" },
  { name: "Hayaati Blue / Pink Perfume 100ml", qty: 2, costPrice: 20500, category: "perfume" },
  { name: "Hayaati Black Perfume Lattafa", qty: 1, costPrice: 16500, category: "perfume" },
  { name: "My Way Perfume 100ml", qty: 2, costPrice: 160000, category: "perfume" },
  { name: "Petra Lattafa Perfume 100ml", qty: 2, costPrice: 30500, category: "perfume" },
  { name: "Intense Noir Perfume 100ml", qty: 2, costPrice: 21100, category: "perfume" },
  { name: "Rayhaan Tiger 100ml", qty: 2, costPrice: 35500, category: "perfume" },
  { name: "Yara Perfume 100ml", qty: 2, costPrice: 23000, category: "perfume" },
  { name: "Zara Man Perfume 100ml", qty: 2, costPrice: 14300, category: "perfume" },
  { name: "Amante Nocturno Perfume", qty: 2, costPrice: 50000, category: "perfume" },
  { name: "Tofy Caramel Perfume 100ml", qty: 2, costPrice: 11500, category: "perfume" },
  { name: "Marshmallow Perfume Blush (Paris Corner)", qty: 2, costPrice: 35000, category: "perfume" },
  { name: "Angham Perfume 100ml", qty: 2, costPrice: 26100, category: "perfume" },
  { name: "Ajayeb Dubai Perfume 100ml", qty: 2, costPrice: 17800, category: "perfume" },
  { name: "Vintage Radio Perfume 100ml", qty: 2, costPrice: 39800, category: "perfume" },
  { name: "Taskeen Perfume Mix 100ml", qty: 2, costPrice: 19000, category: "perfume" },
  { name: "Georgian's Legend Of Kleopatra 100ml", qty: 2, costPrice: 24000, category: "perfume" },
  { name: "Eclaire Affair Perfume", qty: 2, costPrice: 44000, category: "perfume" },
  { name: "Barez Perfume 100ml", qty: 2, costPrice: 16000, category: "perfume" },
  { name: "Flower Garden Perfume", qty: 2, costPrice: 19000, category: "perfume" },
  { name: "Sugar Green", qty: 2, costPrice: 13500, category: "perfume" },
  { name: "Just Jack 1691 Perfume 100ml Mix", qty: 5, costPrice: 17000, category: "perfume" },
  { name: "Velvet Oud Perfume", qty: 2, costPrice: 20500, category: "perfume" },
  { name: "Qaeed Al Shabaab", qty: 2, costPrice: 21000, category: "perfume" },
  { name: "Tamima Lattafa 100ml", qty: 2, costPrice: 16000, category: "perfume" },
  { name: "Zul Perfume", qty: 2, costPrice: 24000, category: "perfume" },
  { name: "24 Carrat Perfume Mix 100ml", qty: 2, costPrice: 14900, category: "perfume" },
  { name: "Silk Mood Perfume 100ml", qty: 2, costPrice: 12500, category: "perfume" },
  { name: "Viking Perfume 115ml", qty: 2, costPrice: 11900, category: "perfume" },
  { name: "Sehr Lattafa Perfume", qty: 2, costPrice: 47000, category: "perfume" },
  { name: "Memories Man Perfume", qty: 2, costPrice: 17900, category: "perfume" },
  { name: "Confetti Perfume 100ml Mix", qty: 4, costPrice: 11000, category: "perfume" },
  { name: "Barakkat Perfume Mix 100ml", qty: 3, costPrice: 14200, category: "perfume" },
  { name: "Sugar Mummy / Sugar Pink Perfume 100ml", qty: 1, costPrice: 15500, category: "perfume" },
  { name: "Sugar Colours", qty: 2, costPrice: 14150, category: "perfume" },
  { name: "Genie Kaly Perfume 50ml", qty: 4, costPrice: 7300, category: "perfume" },
  { name: "Fakhar Lattafa Perfume 100ml", qty: 1, costPrice: 23000, category: "perfume" },
  { name: "Armaf Odyssey Body Spray 200ml", qty: 5, costPrice: 3370, category: "body" },
  { name: "Tesori Oriente Spray", qty: 2, costPrice: 2700, category: "body" },
  { name: "Lattafa Body Spray 200ml", qty: 6, costPrice: 2500, category: "body" },
  { name: "Victoria World Mist 250ml", qty: 6, costPrice: 3050, category: "body" },
  { name: "Pendora / Lomani Body Mist 236ml", qty: 4, costPrice: 5250, category: "body" },
  { name: "Secrete Amour Body Mist", qty: 3, costPrice: 4100, category: "body" },
  { name: "Clive Dorris Mist 250ml", qty: 2, costPrice: 3900, category: "body" },
  { name: "9PM Deodorant", qty: 12, costPrice: 2750, category: "body" },
  { name: "House Of Kinz Spray", qty: 4, costPrice: 2900, category: "body" },
  { name: "Ossum Spray", qty: 4, costPrice: 3450, category: "body" },
  { name: "Bath & Body Works 236ml", qty: 6, costPrice: 5500, category: "body" },
  { name: "V.V Love Mist 250ml", qty: 6, costPrice: 3100, category: "body" },
  { name: "Nexegy Deodorant", qty: 12, costPrice: 2100, category: "body" },
  { name: "Cuba Mist 100ml", qty: 2, costPrice: 3000, category: "body" },
  { name: "Story Of Love Body Mist", qty: 6, costPrice: 3000, category: "body" },
  { name: "Brosia Body Spray", qty: 5, costPrice: 2600, category: "body" },
  { name: "Matelot Perfume 100ml", qty: 2, costPrice: 12100, category: "perfume" },
  { name: "Matelot Body Mist Mix 250ml", qty: 6, costPrice: 3600, category: "body" },
  { name: "My Dear Body Mist 250ml", qty: 4, costPrice: 3500, category: "body" },
  { name: "Monogotas Mist 100ml", qty: 12, costPrice: 1900, category: "body" },
  { name: "Betress Mist 100ml", qty: 12, costPrice: 2000, category: "body" },
];

export const MARKUP_MULTIPLIER = 1.5;

export function sellPriceFromCost(costPrice: number): number {
  return Math.round(costPrice * MARKUP_MULTIPLIER * 100) / 100;
}

export function slugifyProductName(name: string): string {
  return name
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 80);
}
